name: Bunnyshell - Start Preview Environment
concurrency: bns-start-stop-${{ github.event.issue.number }}
on:
  issue_comment:
    types: [created, edited]
jobs:
  get-token:
    name: Get token
    id: get_token
    uses: bunnyshell/workflows/.github/workflows/get-app-token.yaml@main
    secrets:
        app-private-key: ${{ secrets.BUNNYSHELL_APP_PRIVATE_KEY }}
  start:
    name: Start Environment
    uses: bunnyshell/workflows/.github/workflows/start-env.yaml@main
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      env-name: 'Sylius PR #${{ github.event.issue.number }}'
      allowed-users: ${{ vars.BUNNYSHELL_ALLOWED_USERS }}
      comment-on-pr: true
    secrets:
      github-token: ${{ jobs.get_token.outputs.token }} 
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
