name: Bunnyshell Delete Preview Environment
concurrency:
  group: bns-pr-${{ github.event.number }}
on:
  pull_request_target:
    types: [closed]
    branches:
      - '*'
jobs:
  deploy:
    name: Delete Environment
    runs-on: ubuntu-latest
    steps:
    - name: Prepare vars
      run: |-
        echo "BNS_ENV_NAME=Sylius PR #${{ github.event.number }}" >> "$GITHUB_ENV"
    - name: Check existing Environment
      uses: addnab/docker-run-action@v3
      with:
        image: bunnyshell/cli:latest
        options: -v ${{ github.env }}:/github/envs.txt
        run: |
          set -ex

          BNS_ENV_ID=`bns environments list --search "${{ env.BNS_ENV_NAME }}" --token ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }} --project ${{ vars.BUNNYSHELL_PROJECT_ID }} --non-interactive -o json \
            | jq -r "try ._embedded.item[0].id | select (.!=null)"`
          echo "BNS_ENV_ID=$BNS_ENV_ID" >> /github/envs.txt
    - name: Delete Environment
      uses: addnab/docker-run-action@v3
      if: "${{ env.BNS_ENV_ID != '' }}"
      with:
        image: bunnyshell/cli:latest
        run: |
          bns environments delete --id "${{ env.BNS_ENV_ID }}" --token ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }} --non-interactive
